### ISSUE TITLE
jenkins集成后报错script not yet approved for use

### ISSUE THREAD

**Issue by jinqiu881015** [iSoftStoneGroup/EazyBuilder#26]
org.jenkinsci.plugins.scriptsecurity.scripts.UnapprovedUsageException: script not yet approved for use
	at org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval.using(ScriptApproval.java:489)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition.create(CpsFlowDefinition.java:124)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition.create(CpsFlowDefinition.java:70)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:311)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
Finished: FAILURE

**Comment by jinqiu881015** [comment]
![image](https://user-images.githubusercontent.com/56533359/183620087-85235768-63d1-447b-ae8f-678a1d251ce6.png)
这样配置后，不报错了，谢谢

**Comment by iSoftStoneGroup** [comment]
已解决
